### ISSUE TITLE
[Radio Buttons]: Ability to set default option

### ISSUE THREAD

**Issue by prvnbist** [dailykit/dailykit-ui#16]
**Enhancement**
1. The component should have a way to set default active button.

**Issue**
2. If the height of the radio group exceeds the content's height then the text is no longer vertically aligned.

For ex: if a parent container is a flex div then the height of the container is determined by the children that has the most height than the rest due to this the radio group will take the same height as well.

**Comment by thesanjeevsharma** [comment]
Fixed #1 

Can you give me a screenshot of the second one?

**Comment by prvnbist** [comment]
Here: https://inventory-dailyos.netlify.com/
