### ISSUE TITLE
ux improvements for buttons

### ISSUE THREAD

**Issue by siddhantk232** [dailykit/dailykit-ui#27]
all buttons in HTML when clicked show an outline to show the user that it has been clicked and is focused. But when using hover and other CSS techniques we generally don't need it and also when a button is clicked and there is something to be shown, for example, a tunnel or maybe and alert or a modal, we definitely do not want to show an outline to any of our buttons component.

resolving CSS code: 
```
button {
  outline: 0;
}

```

**Comment by prvnbist** [comment]
That's bad for accessibility, as soon as you remove the focus:outline you prohibit user's ability to use tab key to go through elements, with no focus:outline you can't tell which element you're on. No matter if button or not, if it triggers an action it needs to have hover/focus/blur states.

**Comment by siddhantk232** [comment]
totally forgot the tab key functionality. my bad.
