### ISSUE TITLE
Modification in the Button component.

### ISSUE THREAD

**Issue by siddhantk232** [dailykit/dailykit-ui#28]
We gotta have an option in the Button component for the background color. The ingredients list in the recipe form (inside of a tunnel) needs to have a button with a greyish background.

**Comment by prvnbist** [comment]
@siddhantk232 which frame?

**Comment by siddhantk232** [comment]
> @siddhantk232 which frame?

The tunnel where we allow users to select processing for an ingredient and sachets for each serving.

**Comment by prvnbist** [comment]
That's a ButtonTile component - [Here's](https://dailykit-ui.dailykit.org/?path=/story/tiles--button-tile-variant) the storybook example

**Comment by siddhantk232** [comment]
> That's a ButtonTile component - [Here's](https://dailykit-ui.dailykit.org/?path=/story/tiles--button-tile-variant) the storybook example

I know that ButtonTile exists. I was talking about the grey buttons on the left check the [figma](https://www.figma.com/file/WyulahXDTjgdiNAA2RUbZc/Recipe-app) design
